apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-stateful
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.0.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_CLIENT_PORT
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_TICK_TIME
      volumes:
        - name: zookeeper-db-disk
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-db-disk
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 8Gi