apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: carsharinginfo
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/rentals
        pathType: Prefix
        backend:
          service:
            name: rentals
            port:
              number: 8000
      - path: /api/v1/cars
        pathType: Prefix
        backend:
          service:
            name: cars
            port:
              number: 8000

#This configuration helps to enable clients from outside the cluster to access it